CREATE USER TEST_SCHEMA IDENTIFIED BY test1234;
GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE TRIGGER TO TEST_SCHEMA;
ALTER USER TEST_SCHEMA QUOTA UNLIMITED ON USERS;

CREATE TABLE TEST_SCHEMA.CUSTOMERS (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  CUSTOMER_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE TEST_SCHEMA.ORDERS (
  ORDER_ID NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER,
  ORDER_DATE DATE DEFAULT SYSDATE,
  AMOUNT NUMBER(10,2),
  CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES TEST_SCHEMA.CUSTOMERS(CUSTOMER_ID)
);

CREATE OR REPLACE TRIGGER TEST_SCHEMA.TRG_ORDER_AMOUNT_CHECK
BEFORE INSERT ON TEST_SCHEMA.ORDERS
FOR EACH ROW
BEGIN
  IF :NEW.AMOUNT <= 0 THEN
    RAISE_APPLICATION_ERROR(-20001, '注文金額は1円以上である必要があります。');
  END IF;
END;
/

INSERT INTO TEST_SCHEMA.CUSTOMERS VALUES (1, '田中太郎');
INSERT INTO TEST_SCHEMA.CUSTOMERS VALUES (2, '佐藤花子');
INSERT INTO TEST_SCHEMA.ORDERS VALUES (100, 1, SYSDATE, 5000);
COMMIT;
